FROM node:20-alpine
WORKDIR /app

ENV NODE_ENV=production

COPY package*.json ./
RUN npm ci

COPY tsconfig.json ./
COPY src ./src
RUN mkdir -p uploads arquivos-s3

EXPOSE 3000

CMD ["node", "-r", "ts-node/register/transpile-only", "src/index.ts"]
