FROM node:20-alpine
WORKDIR /app

COPY package*.json ./
RUN npm ci --include=dev

COPY tsconfig.json ./
COPY src ./src
RUN mkdir -p uploads arquivos-s3

ENV NODE_ENV=production

EXPOSE 3000

CMD ["node", "-r", "ts-node/register/transpile-only", "src/index.ts"]
