START TRANSACTION;

CREATE TABLE IF NOT EXISTS solicitacoes_titular (
  id int NOT NULL AUTO_INCREMENT,
  tenant_id int NOT NULL,
  empresa_id int NOT NULL,
  protocolo varchar(40) NOT NULL,
  canal_entrada varchar(50) NULL,
  nome varchar(255) NOT NULL,
  cpf varchar(20) NULL,
  data_nascimento date NULL,
  email varchar(255) NOT NULL,
  telefone varchar(50) NULL,
  endereco text COLLATE utf8mb4_unicode_ci,
  tipo_relacao enum('CLIENTE','EX_CLIENTE','COLABORADOR','CANDIDATO','PARCEIRO','OUTRO') NOT NULL DEFAULT 'OUTRO',
  identificador_interno varchar(100) NULL,
  periodo_relacao varchar(100) NULL,
  tipo_solicitacao enum('ACESSO','CONFIRMACAO','CORRECAO','ANONIMIZACAO_ELIMINACAO','PORTABILIDADE','REVOGACAO_CONSENTIMENTO','INFORMACOES_COMPARTILHAMENTO','OPOSICAO','OUTRO') NOT NULL,
  descricao_pedido text COLLATE utf8mb4_unicode_ci NOT NULL,
  categorias_dados text COLLATE utf8mb4_unicode_ci,
  sistemas text COLLATE utf8mb4_unicode_ci,
  canal_resposta enum('EMAIL','TELEFONE','PORTAL','OUTRO') NOT NULL DEFAULT 'EMAIL',
  idioma varchar(20) NULL,
  declaracao_veracidade tinyint(1) NOT NULL DEFAULT 0,
  ciente_prazo tinyint(1) NOT NULL DEFAULT 0,
  autorizacao_uso tinyint(1) NOT NULL DEFAULT 0,
  status enum('ABERTO','EM_ANALISE','EM_TRATATIVA','CONCLUIDO','NEGADO') NOT NULL DEFAULT 'ABERTO',
  responsavel_id int NULL,
  prazo_resposta date NULL,
  created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_solicitacao_titular_protocolo (tenant_id, protocolo),
  KEY idx_solicitacao_titular_tenant (tenant_id),
  KEY idx_solicitacao_titular_empresa (empresa_id),
  KEY idx_solicitacao_titular_status (status),
  CONSTRAINT fk_solicitacao_titular_empresa FOREIGN KEY (empresa_id) REFERENCES empresas (id) ON DELETE CASCADE,
  CONSTRAINT fk_solicitacao_titular_responsavel FOREIGN KEY (responsavel_id) REFERENCES usuarios (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

COMMIT;
