CREATE TABLE `privacy_cases` (
  `id` int NOT NULL AUTO_INCREMENT,
  `tenant_id` int NOT NULL,
  `empresa_id` int NOT NULL,
  `protocolo` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tipo_case` enum('EVENTO_INCIDENTE') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'EVENTO_INCIDENTE',
  `origem` enum('INTERNO','EXTERNO') COLLATE utf8mb4_unicode_ci NOT NULL,
  `titulo` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `descricao` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` enum('ABERTO','EM_TRIAGEM','EM_ANALISE','DECISAO_COMUNICACAO','CONCLUIDO','DESCARTADO')
    COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ABERTO',
  `severidade` enum('ALTA','MEDIA','BAIXA') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MEDIA',
  `responsavel_id` int DEFAULT NULL,
  `prazo` date DEFAULT NULL,
  `anonimo` tinyint(1) NOT NULL DEFAULT '0',
  `reportante_nome` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reportante_email` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reportante_canal` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `aceita_contato` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_privacy_cases_tenant_protocolo` (`tenant_id`,`protocolo`),
  KEY `idx_privacy_cases_tenant` (`tenant_id`),
  KEY `idx_privacy_cases_empresa` (`empresa_id`),
  KEY `idx_privacy_cases_status` (`status`),
  KEY `idx_privacy_cases_severidade` (`severidade`),
  KEY `idx_privacy_cases_origem` (`origem`),
  KEY `fk_privacy_cases_responsavel` (`responsavel_id`),
  CONSTRAINT `fk_privacy_cases_empresa` FOREIGN KEY (`empresa_id`) REFERENCES `empresas` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_privacy_cases_responsavel` FOREIGN KEY (`responsavel_id`) REFERENCES `usuarios` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `privacy_case_incident_details` (
  `id` int NOT NULL AUTO_INCREMENT,
  `tenant_id` int NOT NULL,
  `privacy_case_id` int NOT NULL,
  `dados_afetados` text COLLATE utf8mb4_unicode_ci,
  `titulares_afetados_estimado` int DEFAULT NULL,
  `impacto_descricao` text COLLATE utf8mb4_unicode_ci,
  `medidas_contencao` text COLLATE utf8mb4_unicode_ci,
  `decisao_comunicar_anpd` enum('PENDENTE','SIM','NAO') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDENTE',
  `decisao_comunicar_titulares` enum('PENDENTE','SIM','NAO') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDENTE',
  `justificativa_decisao` text COLLATE utf8mb4_unicode_ci,
  `data_decisao` datetime DEFAULT NULL,
  `decisao_por_usuario_id` int DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_privacy_case_incident_details_case` (`tenant_id`,`privacy_case_id`),
  KEY `idx_privacy_case_incident_details_tenant` (`tenant_id`),
  KEY `idx_privacy_case_incident_details_case` (`privacy_case_id`),
  KEY `fk_privacy_case_incident_details_decisor` (`decisao_por_usuario_id`),
  CONSTRAINT `fk_privacy_case_incident_details_case` FOREIGN KEY (`privacy_case_id`) REFERENCES `privacy_cases` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_privacy_case_incident_details_decisor` FOREIGN KEY (`decisao_por_usuario_id`) REFERENCES `usuarios` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `privacy_case_timeline` (
  `id` int NOT NULL AUTO_INCREMENT,
  `tenant_id` int NOT NULL,
  `privacy_case_id` int NOT NULL,
  `evento_tipo` enum('CRIACAO','ATUALIZACAO','COMENTARIO','MUDANCA_STATUS','MUDANCA_SEVERIDADE','DECISAO_COMUNICACAO','ANEXO_ADICIONADO','ANEXO_REMOVIDO') COLLATE utf8mb4_unicode_ci NOT NULL,
  `descricao` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `metadata_json` text COLLATE utf8mb4_unicode_ci,
  `criado_por_usuario_id` int DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_privacy_case_timeline_tenant_case` (`tenant_id`,`privacy_case_id`),
  KEY `idx_privacy_case_timeline_tipo` (`evento_tipo`),
  KEY `fk_privacy_case_timeline_usuario` (`criado_por_usuario_id`),
  CONSTRAINT `fk_privacy_case_timeline_case` FOREIGN KEY (`privacy_case_id`) REFERENCES `privacy_cases` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_privacy_case_timeline_usuario` FOREIGN KEY (`criado_por_usuario_id`) REFERENCES `usuarios` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `privacy_case_attachments` (
  `id` int NOT NULL AUTO_INCREMENT,
  `tenant_id` int NOT NULL,
  `privacy_case_id` int NOT NULL,
  `nome_arquivo` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `caminho_arquivo` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tipo_mime` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tamanho_bytes` bigint NOT NULL,
  `hash_arquivo` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `enviado_por_usuario_id` int DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_privacy_case_attachments_tenant_case` (`tenant_id`,`privacy_case_id`),
  KEY `fk_privacy_case_attachments_usuario` (`enviado_por_usuario_id`),
  CONSTRAINT `fk_privacy_case_attachments_case` FOREIGN KEY (`privacy_case_id`) REFERENCES `privacy_cases` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_privacy_case_attachments_usuario` FOREIGN KEY (`enviado_por_usuario_id`) REFERENCES `usuarios` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
